sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- git clone https://github.com/jeedom/plugin-openzwave.git ./openzwave
# build image
- docker build -t kdautrey/rpi-jeedom .
