FROM resin/rpi-raspbian

MAINTAINER kevin.dautrey@gmail.com

RUN apt-get update
RUN apt-get -y dist-upgrade

RUN apt-get -y install wget openssh-server supervisor mysql-client

RUN wget https://raw.githubusercontent.com/jeedom/core/stable/install/install.sh \
  chmod +x install.sh \
  ./install.sh -z
